version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      SU_NAME: ${SU_NAME}
      SU_PASSWORD: ${SU_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
